name: aplicacion_web_grupo2
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Base de datos y HTTP
  supabase_flutter: ^2.0.0
  http: ^1.1.0

  # Estado y navegación
  provider: ^6.1.0
  go_router: ^12.0.0

  # UI y diseño
  google_fonts: ^6.1.0
  intl: ^0.19.0

  # Iconos
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true